-- FCG demo data — generated from lib/data.ts. All profiles and figures are fictional.

insert into public.statuses (id, label_en, label_nl) values
  (0, 'Scouted', 'Gescout'),
  (1, 'Verified', 'Geverifieerd'),
  (2, 'EU trial', 'Stage in Europa'),
  (3, 'Partner academy', 'Partneracademie');
insert into public.position_groups (key, label_en, label_nl, sort) values
  ('gk', 'Goalkeepers', 'Keepers', 0),
  ('def', 'Defenders', 'Verdedigers', 1),
  ('mid', 'Midfielders', 'Middenvelders', 2),
  ('att', 'Attackers', 'Aanvallers', 3);
insert into public.positions (key, group_key, label_en, label_nl, ovr_weights, sort) values
  ('GK', 'gk', 'Goalkeeper', 'Keeper', array[0,0.1,0.2,0.25,0.15,0.3]::numeric(4,2)[], 0),
  ('CB', 'def', 'Centre-back', 'Centrale verdediger', array[0.12,0.1,0.13,0.25,0.2,0.2]::numeric(4,2)[], 1),
  ('FB', 'def', 'Full-back', 'Back', array[0.25,0.15,0.1,0.15,0.25,0.1]::numeric(4,2)[], 2),
  ('DM', 'mid', 'Defensive midfielder', 'Verdedigende middenvelder', array[0.08,0.2,0.22,0.18,0.17,0.15]::numeric(4,2)[], 3),
  ('CM', 'mid', 'Central midfielder', 'Centrale middenvelder', array[0.12,0.22,0.25,0.1,0.18,0.13]::numeric(4,2)[], 4),
  ('AM', 'mid', 'Attacking midfielder', 'Aanvallende middenvelder', array[0.15,0.3,0.28,0.05,0.1,0.12]::numeric(4,2)[], 5),
  ('W', 'att', 'Winger', 'Vleugelspeler', array[0.3,0.28,0.15,0.05,0.12,0.1]::numeric(4,2)[], 6),
  ('ST', 'att', 'Striker', 'Spits', array[0.22,0.22,0.1,0.16,0.1,0.2]::numeric(4,2)[], 7);
insert into public.attributes (idx, key, label_en, label_nl) values
  (0, 'pace', 'Pace', 'Snelheid'),
  (1, 'technique', 'Technique', 'Techniek'),
  (2, 'vision', 'Vision', 'Inzicht'),
  (3, 'physical', 'Physical', 'Fysiek'),
  (4, 'work_rate', 'Work rate', 'Werklust'),
  (5, 'composure', 'Composure', 'Rust');
insert into public.traits (key, label_en, label_nl) values
  ('vision', 'Vision', 'Spelinzicht'),
  ('set', 'Set pieces', 'Standaardsituaties'),
  ('dribble', '1v1 dribbling', '1-tegen-1 dribbel'),
  ('leader', 'Leadership', 'Leiderschap'),
  ('aerial', 'Aerial duels', 'Kopduels'),
  ('calm', 'Composure on the ball', 'Rust aan de bal'),
  ('speed', 'Acceleration', 'Acceleratie'),
  ('finisher', 'Clinical finishing', 'Koele afwerking'),
  ('engine', 'Engine', 'Loopvermogen'),
  ('tackle', 'Ball winning', 'Balverovering'),
  ('reflexes', 'Reflexes', 'Reflexen'),
  ('distribution', 'Distribution', 'Opbouw vanuit achteren'),
  ('weakfoot', 'Two-footed', 'Tweebenig');
insert into public.regions (key, name_en, name_nl, place, lng, lat, iso_codes, active_since, scouts, note_en, note_nl, sort) values
  ('ukraine', 'Ukraine', 'Oekraïne', 'Kharkiv · Dnipro · Zaporizhzhia', 35.5, 48.8, array['804']::text[], 2025, 6, 'Youth academies disrupted by the war. Many players train in temporary halls or have been displaced inside the country.', 'Jeugdopleidingen zijn ontwricht door de oorlog. Veel spelers trainen in tijdelijke hallen of zijn ontheemd binnen het land.', 0),
  ('syria', 'Syria', 'Syrië', 'Aleppo · Idlib', 37, 36, array['760']::text[], 2025, 5, 'Over a decade of conflict left a generation without structured football. We work with community coaches in Aleppo and Idlib.', 'Ruim tien jaar conflict liet een generatie zonder georganiseerd voetbal. We werken samen met buurttrainers in Aleppo en Idlib.', 1),
  ('gaza', 'Gaza', 'Gaza', 'Gaza Strip', 34.4, 31.4, array['275']::text[], 2025, 2, 'Scouting is done remotely: local coaches share match footage, our analysts verify. Players are supported by remote coaching.', 'Scouting gebeurt op afstand: lokale trainers delen wedstrijdbeelden, onze analisten verifiëren. Spelers krijgen coaching op afstand.', 2),
  ('yemen', 'Yemen', 'Jemen', 'Aden', 45, 12.9, array['887']::text[], 2026, 3, 'A football-mad country with almost no youth infrastructure left. Street tournaments are our main scouting ground.', 'Een voetbalgek land met vrijwel geen jeugdinfrastructuur meer. Straattoernooien zijn onze belangrijkste scoutingplek.', 3),
  ('sudan', 'Sudan', 'Soedan', 'Port Sudan · Kassala', 35.5, 17.5, array['729']::text[], 2025, 4, 'Millions displaced since 2023. We scout in safer eastern cities where displaced families have settled.', 'Miljoenen ontheemden sinds 2023. We scouten in veiligere oostelijke steden waar ontheemde gezinnen zich hebben gevestigd.', 4),
  ('southsudan', 'South Sudan', 'Zuid-Soedan', 'Juba', 31.6, 6.5, array['728']::text[], 2025, 4, 'Exceptional athletic talent, very few scouting networks. Partnered with a local school league in Juba.', 'Uitzonderlijk atletisch talent, nauwelijks scoutingnetwerken. Samenwerking met een lokale scholencompetitie in Juba.', 5),
  ('kakuma', 'Kakuma camp', 'Kamp Kakuma', 'Kenya · refugee camp', 34.85, 3.72, array[]::text[], 2026, 3, 'One of the largest refugee camps in the world, home to many South Sudanese and Congolese families. Camp leagues run every weekend.', 'Een van de grootste vluchtelingenkampen ter wereld, met veel Zuid-Soedanese en Congolese gezinnen. Elk weekend worden er kampcompetities gespeeld.', 6),
  ('drc', 'DR Congo', 'DR Congo', 'Goma · Bukavu', 28.9, -1.9, array['180']::text[], 2025, 5, 'Eastern Congo has been unstable for decades. We partner with NGOs running boys’ and girls’ teams around Goma.', 'Oost-Congo is al decennia instabiel. We werken met ngo’s die jongens- en meisjesteams rondom Goma begeleiden.', 7),
  ('afghanistan', 'Afghanistan', 'Afghanistan', 'Kabul · Herat · diaspora', 67.5, 34, array['004','4']::text[], 2026, 2, 'Girls are barred from playing. Our women’s programme focuses on displaced Afghan players who continue training abroad.', 'Meisjes mogen er niet voetballen. Ons vrouwenprogramma richt zich op ontheemde Afghaanse speelsters die in het buitenland doortrainen.', 8),
  ('somalia', 'Somalia', 'Somalië', 'Mogadishu', 45.3, 3.5, array['706']::text[], 2026, 3, 'Football is returning to Mogadishu’s streets. We support a mixed youth programme near the old stadium.', 'Voetbal keert terug in de straten van Mogadishu. We steunen een gemengd jeugdprogramma bij het oude stadion.', 9),
  ('sahel', 'Sahel', 'Sahel', 'Burkina Faso · Mali', -1.6, 13.4, array['854','466']::text[], 2026, 4, 'Armed groups have closed schools and pitches in the north. We scout in cities hosting displaced families.', 'Gewapende groepen hebben scholen en velden in het noorden gesloten. We scouten in steden die ontheemde gezinnen opvangen.', 10);
insert into public.locations (key, name, kind, lng, lat, sort) values
  ('amsterdam', 'Amsterdam', 'hub', 4.9, 52.37, 0),
  ('utrecht', 'Utrecht', 'academy', 5.12, 52.09, 1),
  ('antwerpen', 'Antwerpen', 'academy', 4.4, 51.22, 2),
  ('dusseldorf', 'Düsseldorf', 'academy', 6.77, 51.22, 3),
  ('porto', 'Porto', 'academy', -8.61, 41.15, 4),
  ('lyon', 'Lyon', 'academy', 4.83, 45.76, 5),
  ('kopenhagen', 'Kopenhagen', 'academy', 12.57, 55.68, 6);
insert into public.talents (id, display_name, gender, age, position_key, foot, height_cm, shirt_no, region_key, city, status_id, joined_on, trial_location_key, pace, technique, vision, physical, work_rate, composure, matches, goals, assists, clean_sheets, saves, bio_en, bio_nl, quote_en, quote_nl, sort) values
  ('omar-h', 'Omar H.', 'm', 17, 'AM', 'L', 174, 10, 'syria', 'Aleppo', 2, '2025-03-01', 'utrecht', 78, 86, 88, 62, 74, 80, 24, 9, 14, null, null, 'Learned the game on a concrete square between apartment blocks in Aleppo. Plays between the lines and sees passes nobody else does.', 'Leerde voetballen op een betonnen pleintje tussen flatgebouwen in Aleppo. Speelt tussen de linies en ziet passes die niemand anders ziet.', 'His first touch already sets up his next action. With proper coaching he could run a midfield at a high level.', 'Zijn eerste aanname zet zijn volgende actie al klaar. Met goede begeleiding kan hij op hoog niveau een middenveld dirigeren.', 0),
  ('maksym-k', 'Maksym K.', 'm', 18, 'CB', 'R', 188, 4, 'ukraine', 'Kharkiv', 3, '2025-01-01', 'dusseldorf', 70, 72, 74, 84, 82, 85, 31, 3, 2, null, null, 'Captained his youth team through two seasons of interrupted training. Commanding in the air and calm on the ball under pressure.', 'Was aanvoerder van zijn jeugdteam tijdens twee seizoenen vol onderbroken trainingen. Dominant in de lucht en rustig aan de bal onder druk.', 'Organises the back line like a 25-year-old. Reads danger early and rarely needs to go to ground.', 'Organiseert de achterlinie als een 25-jarige. Ziet gevaar vroeg aankomen en hoeft zelden naar de grond.', 1),
  ('deng-m', 'Deng M.', 'm', 16, 'ST', 'R', 186, 9, 'southsudan', 'Juba', 1, '2025-09-01', null, 88, 74, 66, 80, 78, 72, 18, 21, 4, null, null, 'A late growth spurt turned a quick winger into a powerful number nine. Scored 21 goals in 18 matches on dirt pitches around Juba.', 'Een late groeispurt maakte van een snelle buitenspeler een krachtige nummer negen. Scoorde 21 keer in 18 wedstrijden op zandvelden rond Juba.', 'Raw, but the explosiveness is rare. Attacks the space behind the defence with every single run.', 'Nog ruw, maar die explosiviteit is zeldzaam. Valt bij elke loopactie de ruimte achter de verdediging aan.', 2),
  ('grace-k', 'Grace K.', 'f', 17, 'W', 'L', 165, 11, 'drc', 'Goma', 2, '2025-05-01', 'antwerpen', 92, 82, 74, 64, 80, 76, 20, 12, 9, null, null, 'Plays for a girls’ team run by a local NGO near Goma. Fearless in one-v-ones and relentless when tracking back.', 'Speelt in een meidenteam van een lokale ngo bij Goma. Onbevreesd in een-tegen-een situaties en onvermoeibaar in het terugverdedigen.', 'Changes direction at full speed without losing the ball. The kind of winger defenders hate to face.', 'Verandert op topsnelheid van richting zonder de bal te verliezen. Het type vleugelspeler waar verdedigers een hekel aan hebben.', 3),
  ('yazan-k', 'Yazan K.', 'm', 15, 'CM', 'B', 170, 8, 'syria', 'Idlib', 0, '2026-06-01', null, 72, 80, 82, 58, 86, 74, 11, 2, 6, null, null, 'Grew up in a displacement camp where his father organised the only weekly match. Plays with both feet and never stops moving.', 'Groeide op in een ontheemdenkamp waar zijn vader de enige wekelijkse wedstrijd organiseerde. Speelt met beide benen en staat nooit stil.', 'Very young, very clever. Scans before every reception — something you rarely see without academy coaching.', 'Heel jong, heel slim. Kijkt om zich heen vóór elke aanname — iets wat je zelden ziet zonder academie-opleiding.', 4),
  ('liliia-p', 'Liliia P.', 'f', 18, 'CM', 'R', 170, 6, 'ukraine', 'Dnipro', 3, '2025-02-01', 'kopenhagen', 74, 84, 86, 70, 88, 84, 27, 6, 11, null, null, 'Kept her women’s youth team together after their club stopped operating. Now training with a partner academy in Copenhagen.', 'Hield haar vrouwenjeugdteam bij elkaar toen hun club stopte. Traint nu bij een partneracademie in Kopenhagen.', 'A natural organiser with excellent passing range. Already speaks to teammates like a captain.', 'Een natuurlijke organisator met een uitstekend passbereik. Spreekt ploeggenoten nu al toe als een aanvoerder.', 5),
  ('mahmoud-a', 'Mahmoud A.', 'm', 16, 'GK', 'R', 185, 1, 'gaza', 'Gaza Strip', 1, '2025-07-01', null, 60, 70, 72, 76, 74, 86, 15, null, null, 6, 48, 'Trained on sand pitches, often without nets or proper gloves. Now supported remotely by an FCG goalkeeper coach.', 'Trainde op zandvelden, vaak zonder netten of goede handschoenen. Krijgt nu begeleiding op afstand van een FCG-keeperstrainer.', 'Brave, vocal and quick off his line. His footwork is already ahead of most keepers his age.', 'Moedig, communicatief en snel van zijn lijn. Zijn voetenwerk loopt al voor op de meeste keepers van zijn leeftijd.', 6),
  ('ammar-y', 'Ammar Y.', 'm', 17, 'DM', 'R', 178, 5, 'yemen', 'Aden', 1, '2026-01-01', null, 68, 78, 80, 74, 86, 82, 19, 1, 5, null, null, 'Spotted at a Ramadan street tournament in Aden. Shields the back four and keeps the ball moving with simple, clever passes.', 'Ontdekt tijdens een ramadan-straattoernooi in Aden. Beschermt de verdediging en houdt de bal in beweging met simpele, slimme passes.', 'Always in the right place. Teams with him in midfield simply concede fewer chances.', 'Staat altijd op de juiste plek. Teams met hem op het middenveld krijgen simpelweg minder kansen tegen.', 7),
  ('abdelrahman-o', 'Abdelrahman O.', 'm', 19, 'FB', 'L', 176, 3, 'sudan', 'Port Sudan', 2, '2025-04-01', 'porto', 86, 74, 70, 72, 88, 72, 26, 2, 8, null, null, 'Fled Khartoum with his family in 2023 and kept playing in Port Sudan. An overlapping left-back with endless stamina.', 'Vluchtte in 2023 met zijn familie uit Khartoem en bleef voetballen in Port Sudan. Een opkomende linksback met eindeloos uithoudingsvermogen.', 'Covers the whole flank for ninety minutes. Crossing needs work, but the engine is elite.', 'Bestrijkt negentig minuten lang de hele flank. Zijn voorzetten kunnen beter, maar zijn motor is topniveau.', 8),
  ('peter-l', 'Peter L.', 'm', 17, 'CB', 'L', 191, 15, 'kakuma', 'Kakuma', 1, '2026-03-01', null, 72, 66, 68, 88, 80, 78, 16, 4, 1, null, null, 'Born in Kakuma refugee camp. The tallest player in the camp league and its most feared defender.', 'Geboren in vluchtelingenkamp Kakuma. De langste speler van de kampcompetitie en de meest gevreesde verdediger.', 'Left-footed centre-backs with this frame are rare anywhere in the world. Needs games at a higher level.', 'Linksbenige centrale verdedigers met dit postuur zijn overal ter wereld zeldzaam. Heeft wedstrijden op hoger niveau nodig.', 9),
  ('josue-m', 'Josué M.', 'm', 18, 'ST', 'L', 180, 19, 'drc', 'Bukavu', 1, '2025-11-01', null, 82, 84, 72, 76, 74, 82, 22, 17, 6, null, null, 'Plays in Bukavu’s lakeside youth league. Ice-cold in front of goal and capable of creating his own chances.', 'Speelt in de jeugdcompetitie aan het meer van Bukavu. IJskoud voor de goal en in staat zelf kansen te creëren.', 'Finishes with both power and placement. One of the most complete strikers we have seen in the region.', 'Werkt af met kracht én precisie. Een van de meest complete spitsen die we in de regio hebben gezien.', 10),
  ('farid-n', 'Farid N.', 'm', 18, 'W', 'R', 172, 7, 'afghanistan', 'Kabul', 2, '2026-02-01', 'antwerpen', 90, 84, 76, 62, 78, 74, 17, 10, 7, null, null, 'Futsal player turned winger. His close control comes from years of playing in tight concrete courts in Kabul.', 'Zaalvoetballer die vleugelspeler werd. Zijn balbeheersing komt van jaren spelen op krappe betonnen veldjes in Kabul.', 'Inverted winger with a lethal cut inside. Quick feet in small spaces — very futsal, very modern.', 'Buitenspeler op de verkeerde vleugel met een dodelijke actie naar binnen. Snelle voeten in kleine ruimtes — heel futsal, heel modern.', 11),
  ('shabnam-r', 'Shabnam R.', 'f', 19, 'ST', 'R', 168, 9, 'afghanistan', 'Herat', 3, '2025-01-01', 'utrecht', 80, 82, 78, 70, 84, 86, 29, 23, 8, null, null, 'Had to stop playing in Herat in 2021. Kept training in secret, then abroad. Now part of a partner academy in the Netherlands.', 'Moest in 2021 stoppen met voetballen in Herat. Bleef in het geheim en later in het buitenland trainen. Nu onderdeel van een partneracademie in Nederland.', 'Smart movement, two-touch finishing, and a mentality that is impossible to coach. A true leader.', 'Slimme loopacties, afwerking in twee keer raken en een mentaliteit die je niet kunt aanleren. Een echte leider.', 12),
  ('abdi-w', 'Abdi W.', 'm', 16, 'AM', 'R', 171, 14, 'somalia', 'Mogadishu', 0, '2026-07-01', null, 80, 82, 80, 60, 72, 76, 9, 5, 6, null, null, 'Known on his street as “the magician”. Plays barefoot on sand most of the week and in borrowed boots on match days.', 'Op straat bekend als “de tovenaar”. Speelt het grootste deel van de week op blote voeten in het zand, op wedstrijddagen in geleende schoenen.', 'Pure creativity. Still needs structure and strength, but you cannot teach this kind of imagination.', 'Pure creativiteit. Heeft nog structuur en kracht nodig, maar deze verbeelding kun je niet aanleren.', 13),
  ('hodan-a', 'Hodan A.', 'f', 16, 'FB', 'R', 163, 2, 'somalia', 'Mogadishu', 1, '2026-04-01', null, 84, 72, 70, 66, 90, 72, 12, 1, 4, null, null, 'One of the first girls in Mogadishu’s mixed youth programme. Wins her duels and never gives up on a run.', 'Een van de eerste meisjes in het gemengde jeugdprogramma van Mogadishu. Wint haar duels en geeft een loopactie nooit op.', 'Fierce in the tackle and a constant outlet on the right. Huge room to grow with proper coaching.', 'Fel in de duels en altijd aanspeelbaar op rechts. Enorme groeiruimte met goede begeleiding.', 14),
  ('ibrahim-t', 'Ibrahim T.', 'm', 17, 'DM', 'R', 183, 6, 'sahel', 'Ouagadougou', 2, '2025-06-01', 'lyon', 70, 80, 84, 82, 84, 84, 23, 3, 7, null, null, 'His family left the north of Burkina Faso when his school closed. A tall, elegant six who dictates the tempo.', 'Zijn familie verliet het noorden van Burkina Faso toen zijn school sloot. Een lange, elegante zes die het tempo bepaalt.', 'Rare combination of physical presence and passing quality. Looks unhurried in every situation.', 'Zeldzame combinatie van fysieke aanwezigheid en passkwaliteit. Oogt in elke situatie ontspannen.', 15),
  ('moussa-k', 'Moussa K.', 'm', 15, 'W', 'L', 167, 17, 'sahel', 'Mopti', 0, '2026-08-01', null, 88, 80, 70, 56, 76, 68, 8, 6, 3, null, null, 'The youngest player in our Sahel group. Plays in a riverside league in Mopti and is already the fastest on the pitch.', 'De jongste speler in onze Sahel-groep. Speelt in een competitie aan de rivier in Mopti en is nu al de snelste op het veld.', 'Early days, but the acceleration over five metres is outstanding. One to follow closely.', 'Nog vroeg, maar zijn acceleratie over vijf meter is uitzonderlijk. Iemand om nauw te volgen.', 16),
  ('artem-s', 'Artem S.', 'm', 16, 'GK', 'L', 190, 12, 'ukraine', 'Zaporizhzhia', 0, '2026-05-01', null, 58, 66, 70, 80, 72, 78, 12, null, null, 4, 37, 'Kept training after his club’s stadium was damaged. Big frame, big reach, and a very calm voice behind the defence.', 'Bleef trainen nadat het stadion van zijn club beschadigd raakte. Groot postuur, groot bereik en een rustige stem achter de verdediging.', 'Commands his box on crosses. Needs specialist coaching on footwork — the base is very promising.', 'Beheerst zijn zestien bij voorzetten. Heeft specialistische training nodig op voetenwerk — de basis is veelbelovend.', 17),
  ('karim-s', 'Karim S.', 'm', 18, 'FB', 'R', 177, 22, 'gaza', 'Gaza Strip', 1, '2025-08-01', null, 82, 76, 72, 70, 84, 74, 14, 1, 6, null, null, 'Verified through footage shared by his former coach. A modern full-back who is comfortable on both flanks.', 'Geverifieerd via beelden die zijn voormalige trainer deelde. Een moderne back die zich op beide flanken thuis voelt.', 'Two-footed, quick and brave. Would benefit enormously from a stable training environment.', 'Tweebenig, snel en moedig. Zou enorm profiteren van een stabiele trainingsomgeving.', 18),
  ('amina-e', 'Amina E.', 'f', 17, 'CB', 'R', 172, 5, 'sudan', 'Kassala', 0, '2026-08-01', null, 70, 70, 72, 80, 82, 80, 10, 1, 0, null, null, 'Plays in a girls’ team set up by displaced teachers in Kassala. Strong in the air and the team’s natural captain.', 'Speelt in een meidenteam dat door ontheemde leraren in Kassala is opgezet. Sterk in de lucht en de natuurlijke aanvoerder van het team.', 'Reads the game well and organises loudly. Exactly the profile women’s academies are looking for.', 'Leest het spel goed en coacht luid. Precies het profiel waar vrouwenacademies naar zoeken.', 19);
insert into public.talent_traits (talent_id, trait_key, sort) values
  ('omar-h', 'vision', 0),
  ('omar-h', 'set', 1),
  ('omar-h', 'dribble', 2),
  ('maksym-k', 'aerial', 0),
  ('maksym-k', 'leader', 1),
  ('maksym-k', 'calm', 2),
  ('deng-m', 'speed', 0),
  ('deng-m', 'finisher', 1),
  ('deng-m', 'aerial', 2),
  ('grace-k', 'speed', 0),
  ('grace-k', 'dribble', 1),
  ('grace-k', 'engine', 2),
  ('yazan-k', 'engine', 0),
  ('yazan-k', 'vision', 1),
  ('yazan-k', 'weakfoot', 2),
  ('liliia-p', 'leader', 0),
  ('liliia-p', 'vision', 1),
  ('liliia-p', 'set', 2),
  ('mahmoud-a', 'reflexes', 0),
  ('mahmoud-a', 'distribution', 1),
  ('mahmoud-a', 'calm', 2),
  ('ammar-y', 'tackle', 0),
  ('ammar-y', 'calm', 1),
  ('ammar-y', 'engine', 2),
  ('abdelrahman-o', 'speed', 0),
  ('abdelrahman-o', 'engine', 1),
  ('abdelrahman-o', 'tackle', 2),
  ('peter-l', 'aerial', 0),
  ('peter-l', 'tackle', 1),
  ('peter-l', 'leader', 2),
  ('josue-m', 'finisher', 0),
  ('josue-m', 'dribble', 1),
  ('josue-m', 'calm', 2),
  ('farid-n', 'speed', 0),
  ('farid-n', 'dribble', 1),
  ('farid-n', 'finisher', 2),
  ('shabnam-r', 'finisher', 0),
  ('shabnam-r', 'leader', 1),
  ('shabnam-r', 'calm', 2),
  ('abdi-w', 'dribble', 0),
  ('abdi-w', 'vision', 1),
  ('abdi-w', 'set', 2),
  ('hodan-a', 'engine', 0),
  ('hodan-a', 'tackle', 1),
  ('hodan-a', 'speed', 2),
  ('ibrahim-t', 'tackle', 0),
  ('ibrahim-t', 'vision', 1),
  ('ibrahim-t', 'leader', 2),
  ('moussa-k', 'speed', 0),
  ('moussa-k', 'dribble', 1),
  ('artem-s', 'reflexes', 0),
  ('artem-s', 'aerial', 1),
  ('karim-s', 'engine', 0),
  ('karim-s', 'speed', 1),
  ('karim-s', 'weakfoot', 2),
  ('amina-e', 'aerial', 0),
  ('amina-e', 'leader', 1),
  ('amina-e', 'tackle', 2);
insert into public.partnership_tiers (key, name, price_eur, period, featured, sort) values
  ('scout_access', 'Scout Access', 1900, 'season', false, 0),
  ('academy_partner', 'Academy Partner', 7500, 'season', true, 1),
  ('founding_partner', 'Founding Partner', null, 'season', false, 2);
insert into public.donation_impact_items (key, cost_eur, sort) values
  ('train', 15, 0),
  ('boots', 40, 1),
  ('docs', 120, 2),
  ('kit', 220, 3),
  ('trial', 650, 4);
insert into public.fund_allocation (key, label_en, label_nl, percent, sort) values
  ('al1', 'Programmes on the ground', 'Programma’s ter plaatse', 62, 0),
  ('al2', 'Pathway: documents, travel, trials', 'Traject: documenten, reizen, stages', 18, 1),
  ('al3', 'Safeguarding & education', 'Bescherming & onderwijs', 12, 2),
  ('al4', 'Operations', 'Organisatie', 8, 3);
insert into public.team_members (initials, role_en, role_nl, sort) values
  ('FD', 'Founder & director', 'Oprichter & directeur', 0),
  ('HS', 'Head of scouting', 'Hoofd scouting', 1),
  ('WL', 'Welfare & safeguarding lead', 'Leider welzijn & bescherming', 2),
  ('PC', 'Partnerships & clubs', 'Partnerschappen & clubs', 3),
  ('DA', 'Video & data analyst', 'Video- & data-analist', 4);
insert into public.site_metrics (key, value, suffix, label_en, label_nl, sort) values
  ('players_in_pathway', 140, '+', 'Players in the pathway', 'Spelers in het traject', 0),
  ('partner_academies', 12, '', 'Partner academies', 'Partneracademies', 1);
